spring:
  application:
    name: housing-fund
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true
    open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:social_server"
    username: sa
    password:
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        type: trace
